# Simple configuration for testing availability
server {
    listen 127.0.0.1:8090;
    server_name localhost;
    root ./html/default;
    
    # Default index files
    index index.html index.htm;
    
    # Root location
    location / {
        # Allow GET, POST, and DELETE methods
        limit_except GET POST DELETE;
        
        # Enable directory listing
        autoindex on;
    }
    
    # CGI location
    location /cgi-bin {
        limit_except GET POST;
        cgi_ext .py /usr/bin/python3;
        cgi_ext .pl /usr/bin/perl;
        cgi_ext .sh /bin/bash;
        cgi_dir /cgi-bin;
        autoindex off;
    }
}
