# Configuration with multiple servers
server {
    listen 127.0.0.1:8090;
    server_name server1;
    root ./html/default;
    
    # Default index files
    index index.html index.htm;
    
    # Root location
    location / {
        limit_except GET POST DELETE;
        autoindex on;
    }
}

server {
    listen 127.0.0.1:8091;
    server_name server2;
    root ./html/default;
    
    # Default index files
    index index.html index.htm;
    
    # Root location
    location / {
        limit_except GET;
        autoindex off;
    }
}
