server {
    listen 127.0.0.1:8080;
    server_name localhost;
    root ./html/simple_test;
    
    # Default index files
    index index.html;
    
    # Maximum client body size (10MB)
    client_max_body_size 10m;
    
    # Root location
    location / {
        # Allow all methods
        limit_except GET POST DELETE;
        
        # Enable directory listing
        autoindex on;
    }
}
