server {
    listen 8080;
    server_name localhost;
    root /tmp/www;

    location / {
        root /tmp/www;
        index index.html;
        autoindex on;
        limit_except GET POST DELETE;
        client_max_body_size 10485760; # 10MB
    }

    location /cgi-bin {
        root /tmp/www;
        cgi_handler .py /usr/bin/python3;
        limit_except GET POST;
        client_max_body_size 10485760; # 10MB
    }
}
