#!/usr/bin/env python3

import os
import sys

# Print CGI headers
print("Content-Type: text/html")
print()  # Empty line to separate headers from body

# Print HTML content
print("<!DOCTYPE html>")
print("<html>")
print("<head>")
print("    <title>CGI Test</title>")
print("</head>")
print("<body>")
print("    <h1>Hello from CGI!</h1>")
print("    <p>This page was generated by a Python CGI script.</p>")
print("    <h2>Environment Variables:</h2>")
print("    <ul>")

# Print some environment variables
for var in sorted(os.environ.keys()):
    print(f"        <li><strong>{var}</strong>: {os.environ[var]}</li>")

print("    </ul>")

# Print query string parameters if any
if os.environ.get("QUERY_STRING"):
    print("    <h2>Query Parameters:</h2>")
    print("    <ul>")
    for param in os.environ["QUERY_STRING"].split("&"):
        if "=" in param:
            key, value = param.split("=", 1)
            print(f"        <li><strong>{key}</strong>: {value}</li>")
        else:
            print(f"        <li>{param}</li>")
    print("    </ul>")

# Print POST data if any
if os.environ.get("REQUEST_METHOD") == "POST" and os.environ.get("CONTENT_LENGTH"):
    content_length = int(os.environ["CONTENT_LENGTH"])
    post_data = sys.stdin.read(content_length)
    print("    <h2>POST Data:</h2>")
    print(f"    <pre>{post_data}</pre>")

print("</body>")
print("</html>")
