#!/usr/bin/env python3

import os
import sys
import datetime

# Print HTTP headers
print("Content-type: text/html")
print()  # Empty line to separate headers from body

# Print HTML content
print("""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CGI Script Example</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
            color: #333;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 5px;
            background-color: #f9f9f9;
        }
        h1 {
            color: #2c3e50;
            text-align: center;
        }
        h2 {
            color: #3498db;
            margin-top: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
        }
        tr:hover {
            background-color: #f5f5f5;
        }
        footer {
            margin-top: 20px;
            text-align: center;
            font-size: 0.8em;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>CGI Script Example</h1>
        <p>This page is generated by a Python CGI script running on the Webserv HTTP server.</p>
""")

# Server information
print("<h2>Server Information</h2>")
print("<table>")
print("<tr><th>Item</th><th>Value</th></tr>")
print(f"<tr><td>Date and Time</td><td>{datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</td></tr>")
print(f"<tr><td>Server Software</td><td>{os.environ.get('SERVER_SOFTWARE', 'Unknown')}</td></tr>")
print(f"<tr><td>Server Protocol</td><td>{os.environ.get('SERVER_PROTOCOL', 'Unknown')}</td></tr>")
print(f"<tr><td>Server Name</td><td>{os.environ.get('SERVER_NAME', 'Unknown')}</td></tr>")
print(f"<tr><td>Gateway Interface</td><td>{os.environ.get('GATEWAY_INTERFACE', 'Unknown')}</td></tr>")
print("</table>")

# Request information
print("<h2>Request Information</h2>")
print("<table>")
print("<tr><th>Item</th><th>Value</th></tr>")
print(f"<tr><td>Request Method</td><td>{os.environ.get('REQUEST_METHOD', 'Unknown')}</td></tr>")
print(f"<tr><td>Request URI</td><td>{os.environ.get('REQUEST_URI', 'Unknown')}</td></tr>")
print(f"<tr><td>Query String</td><td>{os.environ.get('QUERY_STRING', 'None')}</td></tr>")
print(f"<tr><td>Script Name</td><td>{os.environ.get('SCRIPT_NAME', 'Unknown')}</td></tr>")
print(f"<tr><td>Script Filename</td><td>{os.environ.get('SCRIPT_FILENAME', 'Unknown')}</td></tr>")
print("</table>")

# HTTP Headers
print("<h2>HTTP Headers</h2>")
print("<table>")
print("<tr><th>Header</th><th>Value</th></tr>")
for key, value in os.environ.items():
    if key.startswith('HTTP_'):
        header = key[5:].replace('_', '-').title()
        print(f"<tr><td>{header}</td><td>{value}</td></tr>")
print("</table>")

# Environment Variables
print("<h2>All Environment Variables</h2>")
print("<table>")
print("<tr><th>Variable</th><th>Value</th></tr>")
for key in sorted(os.environ.keys()):
    print(f"<tr><td>{key}</td><td>{os.environ[key]}</td></tr>")
print("</table>")

# Footer
print("""
        <p><a href="/">Back to homepage</a></p>
        
        <footer>
            Webserv - HTTP/1.1 Server in C++98
        </footer>
    </div>
</body>
</html>
""")
